Strings = {

    -- Go on/off duty new
    on_duty = 'Entrar de Serviço',
    on_duty_desc = 'Entraste em serviço!',
    off_duty = 'Saír de serviço',
    off_duty_desc = 'Saíste de serviço!',

    -- QbCore support (1.3.0)
    amount = 'Valor',
    mr = 'Sr',
    mrs = 'Sra',
    debt_collection = 'Cobrança de dívidas',
    db_email = 'Querido %s %s, <br /><br />A Central de Arrecadações Judiciais (CAJ) cobrou as multas que você recebeu da polícia.<br />Foram <strong>$%s</strong> retirado da sua conta.<br /><br />Com os Melhores cumprimentos,<br />Sr. Rúben',
    fine_sent = 'Faturas enviada',
    fine_sent_desc = 'Você enviou multa para $%s!',
    fine_received = 'Fatura recebida',
    fine_received_desc = 'Recebeste uma fatura de $%s',

    -- Death discord logs (1.2.9)
    log_killed_title = 'Jogador Morto',
    log_killed_desc = '> *%s [%s] morto %s [%s]\n\n**Killer\'s Information:**\nName: `%s`\nPlayer ID: `%s`\nIdentifier: `%s`\nSteam: `%s`\nDiscord: `%s`\nLicense: `%s`\nLicense2: `%s`\nXBL: `%s`\nFiveM: `%s`\nIP: ||%s||\n\n**Victim\'s Information:**\nCharacter Name: `%s`\nPlayer ID: `%s`\nIdentifier: `%s`\nSteam: `%s`\nDiscord: `%s`\nLicense: `%s`\nLicense2: `%s`\nXBL: `%s`\nFiveM: `%s`\nIP: ||%s||\n\n> **Death Cause:** `%s`',
    log_suicide_title = 'Jogador cometeu suicidio',
    log_suicide_desc = '> %s [%s] killed themselves\n\n**Player Information:**\nName: `%s`\nPlayer ID: `%s`\nIdentifier: `%s`\nSteam: `%s`\nDiscord: `%s`\nLicense: `%s`\nLicense2: `%s`\nXBL: `%s`\nFiveM: `%s`\nIP: ||%s||\n\n> **Death Cause:** `%s`',
    unknown = 'Desconhecido',


    -- Revive discord logs (1.4.6)
    log_admin_revive_title = 'Player Admin Revived',
    log_admin_revive_desc = '> *%s [%s] admin revived %s [%s]\n\n**Target\'s Information:**\nName: `%s`\nPlayer ID: `%s`\nIdentifier: `%s`\nSteam: `%s`\nDiscord: `%s`\nLicense: `%s`\nLicense2: `%s`\nXBL: `%s`\nFiveM: `%s`\nIP: ||%s||\n\n**Admin\'s Information:**\nCharacter Name: `%s`\nPlayer ID: `%s`\nIdentifier: `%s`\nSteam: `%s`\nDiscord: `%s`\nLicense: `%s`\nLicense2: `%s`\nXBL: `%s`\nFiveM: `%s`\nIP: ||%s||',
    log_self_revive_title = 'Admin Self Revived',
    log_self_revive_desc = '> %s [%s] self revived\n\n**Player Information:**\nName: `%s`\nPlayer ID: `%s`\nIdentifier: `%s`\nSteam: `%s`\nDiscord: `%s`\nLicense: `%s`\nLicense2: `%s`\nXBL: `%s`\nFiveM: `%s`\nIP: ||%s||',
    log_death_logs = 'Logs de Morte',
    log_revive_logs = 'Logs de revive',

    medbag_crutch = 'Muleta',
    medbag_crutch_desc = 'Uma muleta para ajudar os pacientes a caminhar',
    menu_crutch = 'Aplicar muleta',
    menu_crutch_desc = 'Aplica uma muleta ao paciente mais próximo',

    -- Wheelchair strings(1.2.8)
    medbag_chair = 'Cadeira de rodas',
    medbag_chair_desc = 'Uma cadeira de rodas para ajudar pacientes que não podem andar',
    menu_chair = 'Aplicar cadeira de rodas',
    menu_chair_desc = 'Adicionar uma cadeira de rodas a um paciente próximo',
    --end


    shot = 'Tiro',
    stabbed = 'Esfaqueado',
    beat = 'Soco',
    burned = 'Queimado',

    JobMenuTitle = 'MENU INEM',
    dispatch = 'Chamadas',
    dispatch_desc = 'Verifica os cidadãos que necessitam de assitência',
    DispatchMenuTitle = 'Chamadas',
    GoBack = 'Voltar',
    key_map_text = 'INEM',
    assistance_title = 'Pedido de assitência',
    assistance_desc = 'Uma pessoa enviou um pedido de assitência!',
    respawn_available_in = 'Respawn disponível em ~b~%s minutos %s segundos~s~\n',
    respawn_bleedout_in = 'Vais morrer em ~b~%s minutos %s segundos~s~\n',
    respawn_bleedout_prompt = 'Pressiona [~b~E~s~] para dar o fim',
    distress_send = 'Pressiona [~b~G~s~] para enviar sinal de socorro para o INEM',
    distress_sent_title = 'Assistência Solicitada',
    distress_sent_desc = 'O sinal de socorro foi enviado para as unidades disponíveis!',
    route_set_title = 'Destino',
    route_set_desc = 'Um ponto de referência foi definido para a pessoa em perigo!',
    diagnose_patient = 'Diagnóstico',
    diagnose_patient_desc = 'Diagnosticar a pessoa ferida mais próxima',
    no_requests = 'Nenhuma solicitação ativa',
    revive_patient = 'Reanimar',
    revive_patient_desc = 'Tentativa de reanimar pessoa próxima',
    heal_patient = 'Curar',
    heal_patient_desc = 'Tentativa de curar a pessoa mais próxima',
    sedate_patient = 'Sedar',
    sedate_patient_desc = 'Sedar temporariamente uma pessoa próxima',
    drag_patient = 'Arrastar',
    drag_patient_desc = 'Arraste a pessoa ferida próxima',
    place_stretcher_target = 'Adicionar ou Remover paciente',
    place_patient = 'Colocar/Retirar do veículo',
    place_patient_desc = 'Colocar a pessoa próxima dentro/fora do veículo',
    no_nearby = 'Não encontrado',
    no_nearby_desc = 'Parece não haver ninguém por perto',
    no_injury = 'Sem Ferimentos',
    no_injury_desc = 'A pessoa não parece precisar de nenhum tratamento adicional',
    player_injury = 'Pessoa ferida',
    player_injury_desc = 'Esta pessoa parece ter sido %s',
    player_not_unconcious = 'Pessoa consciente',
    player_not_unconcious_desc = 'Parece que o jogador está consciente',
    player_unconcious = 'Pessoa incosnciente',
    player_unconcious_desc = 'O paciente deve estar consciente para este tratamento!',
    player_reviving = 'A reanimar',
    player_reviving_desc = 'Reanimação em progresso',
    player_noitem = 'Falta algum Material',
    player_noitem_desc = 'Você não tem o material necessário para isso!',
    player_successful_revive = 'Reanimado',
    player_successful_revive_reward_desc = 'Você reanimou o paciente com sucesso e ganhou $%s!',
    player_successful_revive_desc = 'Reanimaste o paciente com sucesso!',
    player_healing = 'A curar',
    player_healing_desc = 'Cura do paciente em andamento',
    player_successful_heal = 'Tratado',
    player_successful_heal_desc = 'Paciente tratado com sucesso!',
    player_healed_desc = 'Você foi curado com sucesso pelo médico!',
    not_medic = 'Não autorizado',
    not_medic_desc = 'Não tens as habititações para utilzar isto!',
    target_sedated = 'Sedado',
    target_sedated_desc = 'Foste sedado por um médico',
    player_successful_sedate_desc = 'Sedaste o paciente com sucesso',
    drop_bag_ui = '[E] - Soltar mala',
    drop_stretch_ui = '[E] - Coloque a maca',
    pickup_bag_target = 'Pegar',
    move_target = 'Mover',
    interact_bag_target = 'Abrir',
    successful = 'Bem-Sucedido',
    medbag_pickup = 'Pegaste o saco',
    medbag_pickup_civ = 'Você revistou a bolsa e pegou o que seria útil',
    stretcher_pickup = 'Você pegou a maca dobrável',
    medbag = 'Saco médico',
    medbag_tweezers = 'Pinças',
    medbag_tweezers_desc = 'Usado para remover balas',
    medbag_suture = 'Kit de sutura',
    medbag_suture_desc = 'Usado para costurar feridas',
    medbag_icepack = 'Saco de Gelo',
    medbag_icepack_desc = 'Usado para reduzir o inchaço',
    medbag_burncream = 'Creme para queimaduras',
    medbag_burncream_desc = 'Usado para tratar queimaduras',
    medbag_defib = 'Desfibrilador',
    medbag_defib_desc = 'Para reanimar pacientes',
    medbag_medikit = 'Kit Médico',
    medbag_medikit_desc = 'Usado para tratar dos pacientes',
    medbag_sedative = 'Sedativo',
    medbag_sedative_desc = 'Usado para sedar os pacientes',
    medbag_stretcher = 'Maca dobrável',
    medbag_stretcher_desc = 'Usado para mover pacientes',
    item_grab = 'Retiraste o material do teu saco médico',
    wrong_equipment = 'Equipamento errado!',
    wrong_equipment_desc = 'Foste treinado?',
    player_not_injured = 'Não Ferido',
    player_not_injured_desc = 'Esta pessoa não parece precisar de nenhum tratamento extra e está liberada para o desfibrilador',
    player_treated = 'Tratado',
    player_treated_desc = 'Trataste o paciente com sucesso',
    revive_command_help = 'Um comando admin para reviver os jogadores',
    revive_command_arg = 'O id do jogador',
    reviveall_command_help = 'Um comando admin para reviver todos os jogadores',
    revivearea_command_help = 'Um comando admin para reviver os jogadores próximos',
    revivearea_command_arg = 'Área para reviver os jogadores',
    resetdeathcount_command_help = 'Um comando admin para redefinir a contagem de mortes dos jogadores',
    resetdeathcount_command_arg = 'O id do jogadr',
    viewdeathcount_command_help = 'Um comando para ver sua contagem de mortes',
    alive_again = 'Vivo',
    alive_again_desc = 'Você foi deixado por um local no hospital!',
    request_supplies_target = 'Suprimentos médicos',
    currency = '€',
    not_enough_funds = 'Dinheiro insuficiente',
    not_enough_funds_desc = 'Não possuis dinheiro suficiente!',
    hospital_garage = 'Hospital Garage',
    used_meditkit = 'Kit médico usado',
    used_medikit_desc = 'Conseguiste consertar-te',
    action_cancelled = 'Ação cancelada',
    action_cancelled_desc = 'Cancelaste a tua última ação!',
    healing_self_prog = 'A tratar feridas',
    checkin_hospital = 'Bem Sucedido',
    checkin_hospital_desc = 'Você foi tratado com sucesso pela equipe do hospital',
    max_ems = 'Médicos disponiveis',
    max_ems_desc = 'Há muitos médicos na cidade! Aflição por ajuda!',
    player_busy = 'Ocupado',
    player_busy_desc = 'No momento, você está muito ocupado para fazer esta ação!',
    cloakroom = 'Muda-Roupa',
    civilian_wear = 'Roupa de cívil',
    bill_patient = 'Enviar fatura ao paciente',
    bill_patient_desc = 'Envia uma fatura a um paciente próximo',
    invalid_entry = 'Inválido',
    invalid_entry_desc = 'Sua entrada foi inválida!',
    medical_services = 'Serviços médicos',
    hospital = 'Hospital',

    interact_stretcher_ui = '[E] - Interação',
    stretcher_menu_title = 'Interações da maca',
    open_shop_ui = '[E] - Abrir farmácia',
    
}
